version: '3'

services:
  python-service:
    build: python-service
    ports:
      - "8001:5000"
    image: jor2/python-service
  go-service:
    build: go-service
    ports:
      - "8002:6000"
    image: jor2/go-service
  javascript-service:
    build: javascript-service
    ports:
      - "8003:4000"
    image: jor2/javascript-service